import {Majors} from './majors.enum';

export const MajorsList = [
    `${Majors.MPI}`,
    `${Majors.CBA}`,
    `${Majors.GL}2`,
    `${Majors.RT}2`,
    `${Majors.IIA}2`,
    `${Majors.IMI}2`,
    `${Majors.BIO}2`,
    `${Majors.CH}2`,
    `${Majors.GL}3`,
    `${Majors.RT}3`,
    `${Majors.IIA}3`,
    `${Majors.IMI}3`,
    `${Majors.BIO}3`,
    `${Majors.CH}3`,
    `${Majors.GL}4`,
    `${Majors.RT}4`,
    `${Majors.IIA}4`,
    `${Majors.IMI}4`,
    `${Majors.BIO}4`,
    `${Majors.CH}4`,
    `${Majors.GL}5`,
    `${Majors.RT}5`,
    `${Majors.IIA}5`,
    `${Majors.IMI}5`,
    `${Majors.BIO}5`,
    `${Majors.CH}5`,
    ];
